### PR TITLE
rig up examples

### PR DESCRIPTION
**Pull request by Rich-Harris**
This adds a basic mechanism for creating and selecting examples (#5)

### CODE REVIEW

**Comment by Rich-Harris** [comment]
For now, it turns all the examples into a module that gets inlined in the app bundle – if we find it gets too large we could output it as a JSON file and load it asynchronously instead

**Comment by Victorystick** [comment]
Nice! Now I get to see how I should've done with Ractive! :dancer:

**Comment by Victorystick** [comment]
You'll have to merge it yourself since I can't. :stuck_out_tongue_winking_eye:

**Comment by Rich-Harris** [comment]
whoops! you should have admin access now

**Pull request merged**
