### PR TITLE
fix zh docs

### PR DESCRIPTION
**Pull request by UncleBill**
修正词语的错误、语句通顺和括英文单词两侧加空格

//cc @lcxfs1991

### CODE REVIEW

**Comment by lcxfs1991** [comment]
@UncleBill Let me check. Could you leave your wechat id for contact convenience?

**Comment by UncleBill** [comment]
>Could you leave your wechat id for contact convenience?

It's also `unclebill`

**Comment by lukastaegert** [comment]
Is this still relevant? If so, could someone resolve the conflicts so that it can be merged?

**Comment by eight04** [comment]
It seems that zh doc is out of date, including the API reference and options list.

How did you generate documents with different languages?

**Comment by UncleBill** [comment]
It's out of date, and will be closed.

**Pull request closed without merging**
