### PR TITLE
[WIP] fix site

### PR DESCRIPTION
**Pull request by Rich-Harris**
Seems some dependencies are no longer playing nicely with each other, and there was no lockfile. Bringing everything up to date is taking a while and I've run out of time for now, but will come back to this later

### CODE REVIEW

**Comment by lukastaegert** [comment]
Is this in any shape to be merged at the moment? I suppose since the website is broken anyway, there is no danger it is getting worse...

**Comment by Rich-Harris** [comment]
I *guess* so... the REPL is broken but the guide works

**Comment by lukastaegert** [comment]
I took a shot at merging but it seems there still is an issue probably with the SSR :(

**Comment by lukastaegert** [comment]
@Rich-Harris Ok, an update here:

I ended up reverting the merge and force-pushing to master—sorry if this caused any inconvenience for anyone. Thus this branch should NOT BE DELETED but probably used as the basis for a new PR to update the dependencies, otherwise these commits might be lost.

The website and REPL are working again for now. What I did:
* Add a yarn lock-file (seemed to work better than npm)
* Downgrade svelte-loader to the exact version 2.3.3 (no auto-update)

If the dependencies are eventually updated (which I really hope they are), it seems there is an issue in the latest version of svelte-loader that does not seem to trigger locally but triggers on deployment. Really nasty. It might make sense checking the latest changes to this loader and comparing with the stack-trace of the error which can be found e.g. here: #134 .

**Comment by vladshcherbin** [comment]
@lukastaegert this one is related I guess: https://github.com/sveltejs/svelte-loader/issues/63

**Pull request merged**
