### PR TITLE
fix zh docs markdown link & blank space

### PR DESCRIPTION
**Pull request by YunYouJun**
- [x] Use English bracket replace Chinese symbol to fix zh docs markdown link.
- [x] Unify the style that leave blank space between Chinese and English.

### CODE REVIEW

**Comment by qifeng0748** [comment]
It's good! I need this PR fix zh docs link error. 
@lukastaegert MERGE IT, PLEASE!

**Comment by lukastaegert** [comment]
I'll merge it, but it will need to be maintained manually and I have no idea about its quality.

**Comment by lukastaegert** [comment]
Can you say anything about the quality of #189? Should this be merged as well?

**Comment by YunYouJun** [comment]
I didn't make any big changes to the content. 
Just adjust its layout to follow [chinese-copywriting-guidelines](https://github.com/sparanoid/chinese-copywriting-guidelines).
And fixed link errors caused by Chinese symbols.
Thanks.

**Pull request merged**
