### PR TITLE
Show the current Rollup version in the UI

### PR DESCRIPTION
**Pull request by Victorystick**
I know that the current version is displayed in the console, but it wouldn't hurt to display it in the UI for those who don't open theirs.

screen shot 2015-10-27 at 15 31 12

It would be better to do it declaratively. Do you think I should create a Ractive component instead?

### CODE REVIEW

**Comment by Rich-Harris** [comment]
Ah, now you've reminded me that the version on the website is out of date!

> Do you think I should create a Ractive component instead?

Nah, probably overkill for this. (Though Ractive did just get support for [progressively enhancing](http://jsfiddle.net/rich_harris/kxpdgo89/) existing markup, so a future version of rollupjs.org could be fully described as a Ractive app without sacrificing startup speed).

What do you think about putting it next to the library name instead of the strapline?

screen shot 2015-10-27 at 10 46 43 am

(this is just a mockup fiddling in devtools)

Also, I've just realised that PRs to master get built and deployed! :fearful: will have to fix the travis config

**Comment by Victorystick** [comment]
> Ah, now you've reminded me that the version on the website is out of date!

Glad to help out with the little things. :innocent: 

> (this is just a mockup fiddling in devtools)

I started out the same way. I prefer it next to the library name too. :smile: Good idea to fade the version numbers slightly. I'll get on it...

> Also, I've just realised that PRs to master get built and deployed! :fearful: will have to fix the travis config

... but leave that to you.

**Comment by Rich-Harris** [comment]
awesome – will get 0.20.2 out (has a couple small fixes) and update the version on the site

**Comment by Victorystick** [comment]
Alright. Just pushed `updating-to-0.20.1`. Feel free use it as a base. :+1:

**Comment by Rich-Harris** [comment]
Ah, crap – sorry, missed your last comment, I just went and pushed the exact same changes. Too many tabs open!

**Comment by Rich-Harris** [comment]
Have disabled PR builds in the Travis UI

**Pull request merged**
