### PR TITLE
rig up guide generator

### PR DESCRIPTION
**Pull request by Rich-Harris**
**not ready for merge**

Follow up to https://github.com/rollup/rollup/issues/385. I figured it makes sense for tutorials/guides to exist on rollupjs.org, since that's where people are likely to look for them. This PR rigs up a guide generator. It's fairly crude, we just edit [these markdown files](https://github.com/rollup/rollupjs.org/tree/d403b859a297448b8a1483e0a4e1c607e608604e/src/guide) (so it'll be easy for people to contribute) and it glues them together into a single page that looks like this:

screen shot 2015-12-31 at 1 52 03 pm

Just need to add some actual content. (Requirements may change as content gets added, e.g. we may need nested navigation etc. But we can cross that bridge when we come to it.)

### CODE REVIEW

**Comment by Rich-Harris** [comment]
Guides we need (please suggest any I'm missing):

* [ ] **What is Rollup?** What are JavaScript modules, what is bundling, why do we need those things? What does it *make*? (AMD/CJS/UMD/IIFE etc)
* [ ] **Creating your first bundle** Prerequisites (node etc), installing globally and running on the command line
* [ ] **Using config files** Where to put it, what goes in it
* [ ] **Getting started with plugins** How to find them, how to use them, what they do, what order they run in
* [ ] **Using Rollup with Babel** Where does one stop and the other begin? What configuration stuff do I need to know about? Having two separate `.babelrc` files (one for build tool/tests, one for source code)
* [ ] **Using Rollup with modules installed from npm** How to set it up, difference between `main` and `jsnext:main` why tree-shaking doesn't work
* [ ] **Creating sourcemaps**

Advanced guides:

* [ ] Using the JavaScript API
* [ ] Creating plugins
* [ ] Using Rollup in testing
* [ ] Using ES2015 in your build script/config file
* [ ] Distributing your library as an ES2015 module

Misc

* [ ] Comparison with other tools
* [ ] Troubleshooting/FAQs

**Comment by eventualbuddha** [comment]
> - [ ] Using Rollup in testing

This strikes me as one that pretty much everybody is going to want, no? Either that or a recommendation to *not* use Rollup in testing. Essentially, we should spell out the best practice for this.

**Comment by Rich-Harris** [comment]
Definitely agree that it's important. My initial thought was that it should go in 'advanced' because I think it can be a bit off-putting to people who are either new to programming and haven't yet got into the habit of testing, or are just trying to wrap their heads round how to create a UMD build before worrying about different uses. But yeah, it might deserve a place in the basic section if it's a guide from getting to 'what are JS modules?' to 'here is my polished library'.

> Essentially, we should spell out the best practice for this.

Yeah. I daresay this will bear some discussion, because I'm still figuring it out myself. I tend not to bother with unit tests – I only really care about whether the public API behaves as expected – so I tend to create a CJS build in a `pretest` step, and use it as a regular Node.js `require` (albeit possibly via Babel). But if I was more disciplined about unit testing I suspect I would use `multi-entry`. Some 'official' guidance would definitely be a good thing.

**Comment by Rich-Harris** [comment]
Still plenty of stuff to add but I figured a partial guide was better than no guide, so I've published what's there so far. Hopefully we'll get some feedback

**Pull request merged**
