### PR TITLE
deploy to netlify

### PR DESCRIPTION
**Pull request by Rich-Harris**
After this morning's site outage, I think we should migrate to Netlify, which is extremely simple to use and has a good reputation for reliability. Since rollupjs.org is a completely static site, that's fairly straightforward.

This PR doesn't yet include any mechanism for auto-deploying from CI, but I thought I'd get the ball rolling anyway. The site is deployed at https://rollup.netlify.com, and I've updated the DNS settings to point there instead of at Zeit.

### CODE REVIEW

**Comment by lukastaegert** [comment]
Nice! Will this enable people different from you to deploy new versions?

**Comment by Rich-Harris** [comment]
At the moment no. Eventually yes, once it's configured properly it should be possible for anyone with the proper credentials, AFAICT

**Comment by lukastaegert** [comment]
Cool! I would hate very much to bother you for each documentation update 🙄 Seems that netlify are taking continuous deployment serious even on their free tier, nice pick!

**Comment by lukastaegert** [comment]
BTW it seems the new site is up and kicking now without any hick-ups as far as I can tell.

**Comment by lukastaegert** [comment]
Depending on how they handle credentials, I could also take care of setting up CD

**Comment by Rich-Harris** [comment]
well that was... much easier than i expected. nice one, netlify. AAAAAA would deploy again

**Pull request merged**
